
package studentaccommodationsystem;

import java.awt.Color;
import java.awt.HeadlessException;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.JFileChooser;

/**
 *
 * @author taome
 */
public class HMess extends javax.swing.JFrame {
    
    //variable for db connect
    private Connection con;
    private Statement st;
    private PreparedStatement pst;
    private ResultSet rs;
    
    //variable for add image
    String filename = null;
    String abspath = null;
    byte[] photo = null;
    
    String hemail = null;
    String hname = null;
    String mid = null;
    
    public HMess() {
        initComponents();
    }
    public HMess(String email, String name) {
        initComponents();
        hemail = email;
        hname = name;
        userName.setText(hname);
        CName.setText(hname);
        CEmail.setText(hemail);
        getHDetails();
    }
    
    public void getHDetails()
    {
        DBConnect dbc = new DBConnect();
        String sql="Select phonenumber from houseownerdetails where email = '"+hemail+"';";
        try{
            rs = dbc.getDetails(sql);
            while(rs.next())
            {
                cPhone.setText(rs.getString("phonenumber"));
            }
        }catch(SQLException e){
            System.out.println("Error : " + e);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        userButton = new javax.swing.JButton();
        userName = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AdTitle = new javax.swing.JTextField();
        choosePhoto = new javax.swing.JTextField();
        choosePhotoButtton = new javax.swing.JButton();
        monthBox = new javax.swing.JComboBox<>();
        yearBox = new javax.swing.JComboBox<>();
        seatBox = new javax.swing.JComboBox<>();
        messRent = new javax.swing.JTextField();
        fixedRent = new javax.swing.JCheckBox();
        negRent = new javax.swing.JCheckBox();
        areaBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        hDetails = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        hAddress = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cityBox = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        CName = new javax.swing.JTextField();
        cPhone = new javax.swing.JTextField();
        CEmail = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        submitAd = new javax.swing.JButton();
        cancelAd = new javax.swing.JButton();
        statChecker = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Accommodation - Owner");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(61, 204, 61));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userButton.setBackground(new java.awt.Color(0, 151, 230));
        userButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user.png"))); // NOI18N
        userButton.setBorder(null);
        userButton.setBorderPainted(false);
        userButton.setContentAreaFilled(false);
        userButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userButtonMouseExited(evt);
            }
        });
        userButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userButtonActionPerformed(evt);
            }
        });
        jPanel2.add(userButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 40, 50, 50));

        userName.setEditable(false);
        userName.setBackground(new java.awt.Color(61, 204, 61));
        userName.setColumns(10);
        userName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        userName.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        userName.setBorder(null);
        userName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userNameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userNameMouseExited(evt);
            }
        });
        userName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameActionPerformed(evt);
            }
        });
        jPanel2.add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 290, -1));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(61, 204, 61));
        jTextField3.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField3.setText(" House Owner");
        jTextField3.setToolTipText("");
        jTextField3.setBorder(null);
        jTextField3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, 90, 17));

        jLabel15.setBackground(new java.awt.Color(0, 151, 230));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MessClass.png"))); // NOI18N
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 250, 60));

        BackButton.setBackground(new java.awt.Color(61, 204, 61));
        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        BackButton.setBorderPainted(false);
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        jPanel2.add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 40, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 100));

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setBorder(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setAutoscrolls(true);
        jPanel1.setPreferredSize(new java.awt.Dimension(733, 990));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Post_Your_Ads1.png"))); // NOI18N

        AdTitle.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        AdTitle.setForeground(new java.awt.Color(204, 204, 204));
        AdTitle.setText("Enter Title Of Your Advertisement");
        AdTitle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AdTitleFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                AdTitleFocusLost(evt);
            }
        });

        choosePhoto.setEditable(false);
        choosePhoto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        choosePhoto.setForeground(new java.awt.Color(204, 204, 204));
        choosePhoto.setText("Choose Files To Upload");
        choosePhoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        choosePhoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                choosePhotoMousePressed(evt);
            }
        });

        choosePhotoButtton.setText("Choose Files");
        choosePhotoButtton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        choosePhotoButtton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choosePhotoButttonActionPerformed(evt);
            }
        });

        monthBox.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        monthBox.setMaximumRowCount(6);
        monthBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        yearBox.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        yearBox.setMaximumRowCount(5);
        yearBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Year", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));

        seatBox.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        seatBox.setMaximumRowCount(15);
        seatBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Number Of Seats", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        seatBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        messRent.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        messRent.setForeground(new java.awt.Color(204, 204, 204));
        messRent.setText("Rent (Tk)");
        messRent.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                messRentFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                messRentFocusLost(evt);
            }
        });

        fixedRent.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(fixedRent);
        fixedRent.setText("  Fixed");

        negRent.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(negRent);
        negRent.setText("  Negotiable");

        areaBox.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        areaBox.setMaximumRowCount(10);
        areaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Area", "Adabor", "Aftabnagar", "Agargaon", "Ahmed Nagar", "Ahmedbagh", "Alambagh", "Alamganj", "Alinagar", "Alu Bazar", "Amin Bagh", "Angur Jora", "Arambagh", "Asad Gate", "Ashiyan City", "Ashkona", "Ashrafabad", "Atipara", "Azimpur", "Babu Bazar", "Badda", "Baddanagar", "Bagbari", "Bahadurpur", "Baily Square", "Bakshi", "Banagram", "Banani", "Banani DOHS", "Banasree", "Bangla Bazar", "Bangla Motor", "Bangladesh Bank Colony", "Bangsal", "Banianagar", "Bank Colony", "Bara Katra", "Bara Maghbazar", "Barentek", "Baridhara", "Baridhara DOHS", "Bashabo", "Begum Bazar", "Begumganj", "Bibir Bazar", "Bijoynagar", "Boro Moghbazar", "Box Nagar", "Brahman Chiron", "Byshteki", "Chalk Bazar", "Chamilibagh", "Chankharpool", "Chhaya Bithi Housing", "Chhota Katra", "Chowdhury Para Malibagh", "Commissoner Bari", "Companiganj", "Court House Street", "D.I.T.Area", "Dakshin Khan", "Dakshin Mugda Para", "Dalpur", "Darus Salam", "Dawanpara", "Dayaganj", "Dhaka College Area", "Dhaka Medical College", "Dhalka Nagar", "Dhanmondi", "Dholairpar", "Dilkusha", "East Baragram", "Eskaton", "Faidabad", "Fakira Pool", "Farashganj", "Faridabad ", "Gabtoli ", "Ganaktuli ", "Gendaria ", "Goalghat ", "Goalnagar ", "Golartek ", "Goran ", "Gulbagh ", "Gulistan ", "Gulshan -1  ", "Gulshan-2 ", "Gupibagh Haji ", "Para Hasan Nagar ", "Hatirpool Bazar ", "Hatkhola Hazaribagh ", "Hazi Bari ", "Hazrat Nagar ", "Ibrahinpur ", "Islambagh ", "Islamnagar ", "Islampur ", "Jafrabad ", "Jaolahati ", "Jatrabari ", "Jeleypara ", "Jhigatola ", "Jurain ", "Kadamtala ", "Kafrul ", "Kakrail ", "Kalabagan ", "Kamalapur ", "Kaptan Bazar ", "Karatitola ", "Karimullah Bagh ", "Kather Pool ", "Kawranbazar ", "Kazipara ", "Khamer Bari", "Khilgaon ", "Khilkhat ", "Kumartuly ", "Kuril ", "Kusumbag ", "Lakshmi Bazar ", "Lalbagh ", "Lalmatia ", "Madartek ", "Madhu Bazar ", "Malibagh ", "Manikdey ", "Matikata ", "Mazibari ", "Meradia ", "Merul Badda ", "Middle Badda ", "Mir Hazirbagh ", "Mirpur Ceramic ", "Mirpur Colony ", "Mirpur Section-1 ", "Mirpur Section-10  ", "Mirpur Section-11 ", "Mirpur Section-12  ", "Mirpur Section-14 ", "Mirpur Section-2 ", "Mirpur Section-6  ", "Mirpur Section-7  ", "Mohakhali ", "Mohammadpur ", "Mokim Katra ", "Mominbagh ", "Moneshwar ", "Monipur ", "Monipuripara ", "Moshundi ", "Motijheil ", "Moulvi Bazar ", "Munshihati ", "Muradpur-1 ", "Muradpur-2 ", "Murgitola ", "Nabin Bag Bank Colony ", "Nadda Para ", "Namapara ", "Narinda ", "Nawab Katara ", "Nawabbari ", "Naya Bazar ", "Naya Paltan ", "Nazira Bazar ", "Newmarket ", "Neyatola ", "Niketan ", "Nikunjo ", "Nilkhet ", "Nilkhet ", "Babupura ", "North Badda ", "Nowagaon ", "Nowapara ", "Nurerchala ", "Paikpara ", "Parbata ", "Parer Bagh ", "Paribagh ", "Patuatuly ", "Pilkhana ", "Pollabi ", "Postagola ", "Purana Paltan ", "Puratan Mogultoli Purba ", "Purba ", "Razabazar ", "Rajarbagh ", "Ramna ", "Rampura ", "Rasulpur ", "Rayer Bazar ", "Rishi Para ", "Islamabed ", "Rokanpur ", "Royer Bazar ", "Staff Roysaheb Bazar ", "Rupnagar ", "Sabujbagh ", "Saidabad ", "Sawrapara ", "Science Laboratory ", "Segun Bagicha ", "Senpara ", "Shahidbagh ", "Shahidnagar ", "Shahjadpur ", "Shahjahanpur ", "Shakari Nagar ", "Shakertek ", "Shakhari Bazar  ", "Shamibagh ", "Shantibagh ", "Shantinagar ", "Shikaritola ", "Siddeswary ", "Siddique Bazar ", "Sonatengar ", "South Badda ", "Sowarighat ", "Sultanganj", "Takerhat", "Tallabagh ", "Taltola ", "Tegturipara ", "Tejkunipara ", "Tennery ", "Thatary Bazar ", "Topkhana ", "Uttar Khan ", "Uttar Mousondi ", "Uttara ABM City ", "Uttara Model Town ", "Vasantek ", "Wari" }));
        areaBox.setAutoscrolls(true);

        hDetails.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        hDetails.setForeground(new java.awt.Color(51, 51, 51));
        hDetails.setText("Write Description About Mess");
        hDetails.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                hDetailsFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                hDetailsFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(hDetails);

        hAddress.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        hAddress.setForeground(new java.awt.Color(51, 51, 51));
        hAddress.setText("Enter Full Address");
        hAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                hAddressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                hAddressFocusLost(evt);
            }
        });
        jScrollPane2.setViewportView(hAddress);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Title");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Photos");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Date");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Seat");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Rent");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Address");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Area");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Details");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ContactInformation.png"))); // NOI18N

        cityBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select City", "Dhaka" }));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("City");

        CName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        CName.setText("Name");
        CName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                CNameFocusLost(evt);
            }
        });

        cPhone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cPhone.setText("Phone Number");
        cPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cPhoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cPhoneFocusLost(evt);
            }
        });

        CEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        CEmail.setText("E-mail Address");
        CEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                CEmailFocusLost(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Name");

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Phone");

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Email");

        submitAd.setBackground(new java.awt.Color(0, 204, 51));
        submitAd.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        submitAd.setForeground(new java.awt.Color(255, 255, 255));
        submitAd.setText("Submit Ad");
        submitAd.setBorder(null);
        submitAd.setBorderPainted(false);
        submitAd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitAdActionPerformed(evt);
            }
        });

        cancelAd.setBackground(new java.awt.Color(235, 47, 6));
        cancelAd.setForeground(new java.awt.Color(255, 255, 255));
        cancelAd.setText("Cancel");
        cancelAd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelAdActionPerformed(evt);
            }
        });

        statChecker.setBackground(new java.awt.Color(255, 255, 255));
        statChecker.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        statChecker.setForeground(new java.awt.Color(255, 0, 0));
        statChecker.setText("* Photo Size Limit 512 KB");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(AdTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(choosePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(choosePhotoButtton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(seatBox, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(messRent, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(fixedRent, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(negRent))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(cityBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(areaBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(CName, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(cPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel16)
                        .addGap(19, 19, 19)
                        .addComponent(CEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(submitAd, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(statChecker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(monthBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(yearBox, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(cancelAd, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(AdTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(choosePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(choosePhotoButtton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(statChecker)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(messRent, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(fixedRent))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(negRent)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cityBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(areaBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(cPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(submitAd, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(cancelAd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jScrollPane3.getVerticalScrollBar().setUnitIncrement(16);

        jScrollPane3.setViewportView(jPanel1);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 750, 410));

        jMenu1.setText("Menu");

        jMenuItem1.setText("Profile");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("LogOut");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userButtonMouseEntered
        // TODO add your handling code here:

        userButton.setBackground(new Color(0, 151, 230));
        userName.setForeground(new Color(3,118,3));

    }//GEN-LAST:event_userButtonMouseEntered

    private void userButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userButtonMouseExited
        // TODO add your handling code here:

        userButton.setBackground(new Color(0, 151, 230));
        userName.setForeground(Color.BLACK);
    }//GEN-LAST:event_userButtonMouseExited

    private void userNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userNameMouseEntered
        // TODO add your handling code here:

        userName.setForeground(new Color(3,118,3));
    }//GEN-LAST:event_userNameMouseEntered

    private void userNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userNameMouseExited
        // TODO add your handling code here:

        userName.setForeground(Color.BLACK);
    }//GEN-LAST:event_userNameMouseExited

    private void AdTitleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AdTitleFocusGained
        // TODO add your handling code here:
        
        if(AdTitle.getText().trim().equals("Enter Title Of Your Advertisement"))
        {
            AdTitle.setText("");
            AdTitle.setForeground(Color.BLACK);
        }
        
    }//GEN-LAST:event_AdTitleFocusGained

    private void AdTitleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AdTitleFocusLost
        // TODO add your handling code here:
        
        if(AdTitle.getText().equals(""))
        {
            AdTitle.setText("Enter Title Of Your Advertisement");
            AdTitle.setForeground(new Color(204,204,204));
        }
        
    }//GEN-LAST:event_AdTitleFocusLost

    private void messRentFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_messRentFocusGained
        // TODO add your handling code here:
        
        if(messRent.getText().trim().equals("Rent (Tk)"))
        {
            messRent.setText("");
            messRent.setForeground(Color.BLACK);
        }
        
    }//GEN-LAST:event_messRentFocusGained

    private void messRentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_messRentFocusLost
        // TODO add your handling code here:
        
        if(messRent.getText().equals(""))
        {
            messRent.setText("Rent (Tk)");
            messRent.setForeground(new Color(204,204,204));
        }
        
    }//GEN-LAST:event_messRentFocusLost

    private void hAddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hAddressFocusGained
        // TODO add your handling code here:
        
        if(hAddress.getText().trim().equals("Enter Full Address"))
        {
            hAddress.setText("");
            hAddress.setForeground(Color.BLACK);
        }
        
    }//GEN-LAST:event_hAddressFocusGained

    private void hAddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hAddressFocusLost
        // TODO add your handling code here:
        
        if(hAddress.getText().equals(""))
        {
            hAddress.setText("Enter Full Address");
            hAddress.setForeground(new Color(51,51,51));
        }
        
    }//GEN-LAST:event_hAddressFocusLost

    private void hDetailsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hDetailsFocusGained
        // TODO add your handling code here:
        
        if(hDetails.getText().trim().equals("Write Description About Mess"))
        {
            hDetails.setText("");
            hDetails.setForeground(Color.BLACK);
        }
        
    }//GEN-LAST:event_hDetailsFocusGained

    private void hDetailsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hDetailsFocusLost
        // TODO add your handling code here:
        
        if(hDetails.getText().equals(""))
        {
            hDetails.setText("Write Description About Mess");
            hDetails.setForeground(new Color(51,51,51));
        }
        
    }//GEN-LAST:event_hDetailsFocusLost

    private void CNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CNameFocusGained
        // TODO add your handling code here:
        
        if(CName.getText().trim().equals("Name"))
        {
            CName.setText("");
            CName.setForeground(Color.BLACK);
        }
        else if(CName.getText().trim().equals(hname))
        {
            CName.setForeground(Color.BLACK);
        }
        
    }//GEN-LAST:event_CNameFocusGained

    private void CNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CNameFocusLost
        // TODO add your handling code here:
        
        if(CName.getText().equals(""))
        {
            CName.setText("Name");
            CName.setForeground(new Color(204,204,204));
        }
        
    }//GEN-LAST:event_CNameFocusLost

    private void cPhoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cPhoneFocusGained
        // TODO add your handling code here:
        
        if(cPhone.getText().trim().equals("Phone Number"))
        {
            cPhone.setText("");
            cPhone.setForeground(Color.BLACK);
        }
        
    }//GEN-LAST:event_cPhoneFocusGained

    private void cPhoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cPhoneFocusLost
        // TODO add your handling code here:
        
        if(cPhone.getText().equals(""))
        {
            cPhone.setText("Phone Number");
            cPhone.setForeground(new Color(204,204,204));
        }
        
    }//GEN-LAST:event_cPhoneFocusLost

    private void CEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CEmailFocusGained
        // TODO add your handling code here:
        
        if(CEmail.getText().trim().equals("E-mail Address"))
        {
            CEmail.setText("");
            CEmail.setForeground(Color.BLACK);
        }
        else if(CEmail.getText().trim().equals(hemail))
        {
            //CEmail.setText("");
            CEmail.setForeground(Color.BLACK);
        }
        
    }//GEN-LAST:event_CEmailFocusGained

    private void CEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CEmailFocusLost
        // TODO add your handling code here:
        
        if(CEmail.getText().equals(""))
        {
            CEmail.setText("E-mail Address");
            CEmail.setForeground(new Color(204,204,204));
        }
        
    }//GEN-LAST:event_CEmailFocusLost

    private void cancelAdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelAdActionPerformed
        // TODO add your handling code here:
        
        OwnerMainPage omp = new OwnerMainPage(hemail, hname);
        omp.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_cancelAdActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        
        OwnerMainPage omp = new OwnerMainPage(hemail, hname);
        omp.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_BackButtonActionPerformed

    private void submitAdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitAdActionPerformed
        // TODO add your handling code here:
        
        String title = AdTitle.getText();
        String month = monthBox.getSelectedItem().toString();
        String year = yearBox.getSelectedItem().toString();
        String date = month + ", " + year;
        String seat = seatBox.getSelectedItem().toString();
        String mrent = messRent.getText();
        String rtype = null;
        if(fixedRent.isSelected() == true)
        {
            rtype ="(Fixed)";
        }
        else if(negRent.isSelected() == true)
        {
            rtype ="(Negotiable)";
        }
        
        String address = hAddress.getText();
        String city = cityBox.getSelectedItem().toString();
        String area = areaBox.getSelectedItem().toString();
        String details = hDetails.getText();
        String name = CName.getText();
        String phone = cPhone.getText();
        String email = CEmail.getText();
        String userid = null;
        DBConnect dbc = new DBConnect();
        try{
            String sql = "Select userid from houseownerdetails where email = '"+hemail+"'";
            rs = dbc.getDetails(sql);
            while(rs.next())
            {
                userid = rs.getString("userid");
            }
        }catch(SQLException e){
            System.out.println("Error : " + e);
        }
        
        //MessDetails.add(userid);
        
        //database connection
        try {
            Class.forName("com.mysql.jdbc.Driver");
            // step 1 > get a connection to database
            
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/accommodationsystem", "root", "");
            //step 2> create a statement
            st = con.createStatement();
            
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println("Error : " + e);
        }
        
        try{
            String sqlQuery = "insert into messdetails(title, date, seat, rent, address, city, area, details, photo, name, email, phone, renttype, userid) "
                    + "values(?,?,?,?,?,?,?,?,?,?,?,?,?,?);";
            
            pst = con.prepareCall(sqlQuery);
            pst.setString(1, title);
            pst.setString(2, date);
            pst.setString(3, seat);
            pst.setString(4, mrent);
            pst.setString(5, address);
            pst.setString(6, city);
            pst.setString(7, area);
            pst.setString(8, details);
            pst.setBytes(9, photo);
            pst.setString(10, name);
            pst.setString(11, email);
            pst.setString(12, phone);
            pst.setString(13, rtype);
            pst.setString(14, userid);
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Ads Posted! Wait For Verification");
            this.setVisible(false);
            OwnerMainPage omp = new OwnerMainPage(hemail, hname);
            omp.setVisible(true);
            
        }catch(HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, "Enter All Data Correctly");
            System.out.println("Error : " + e);
        }
        
    }//GEN-LAST:event_submitAdActionPerformed

    private void choosePhotoButttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choosePhotoButttonActionPerformed
        // TODO add your handling code here:
        //Add Image
        
        JFileChooser jc = new JFileChooser();
        jc.showOpenDialog(null);
        File f = jc.getSelectedFile();
        
        abspath = f.getAbsolutePath();
        filename = f.getName();
        choosePhoto.setForeground(Color.BLACK);
        choosePhoto.setText(filename);
        try{
            File image = new File(abspath);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            for(int readNum; (readNum = fis.read(buf)) != -1; )
            {
                bos.write(buf, 0, readNum);
            }
            photo = bos.toByteArray();
            
        }catch(IOException e){
            System.out.println("Error : " + e);
        }
        //add Image end
    }//GEN-LAST:event_choosePhotoButttonActionPerformed

    private void choosePhotoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choosePhotoMousePressed
        // TODO add your handling code here:
        
        choosePhotoButtton.doClick();
        
    }//GEN-LAST:event_choosePhotoMousePressed

    private void userButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userButtonActionPerformed
        // TODO add your handling code here:
        
        OwnerProfile op = new OwnerProfile(hemail, hname);
        op.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_userButtonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:

        OwnerProfile op = new OwnerProfile(hemail, hname);
        op.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:

        LogIn lg = new LogIn();
        lg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void userNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameActionPerformed
        // TODO add your handling code here:
        
        userButton.setBackground(new Color(61,204,61));
        OwnerProfile op = new OwnerProfile(hemail, hname);
        op.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_userNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HMess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HMess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HMess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HMess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HMess().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdTitle;
    private javax.swing.JButton BackButton;
    private javax.swing.JTextField CEmail;
    private javax.swing.JTextField CName;
    private javax.swing.JComboBox<String> areaBox;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cPhone;
    private javax.swing.JButton cancelAd;
    private javax.swing.JTextField choosePhoto;
    private javax.swing.JButton choosePhotoButtton;
    private javax.swing.JComboBox<String> cityBox;
    private javax.swing.JCheckBox fixedRent;
    private javax.swing.JTextPane hAddress;
    private javax.swing.JTextPane hDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField messRent;
    private javax.swing.JComboBox<String> monthBox;
    private javax.swing.JCheckBox negRent;
    private javax.swing.JComboBox<String> seatBox;
    private javax.swing.JLabel statChecker;
    private javax.swing.JButton submitAd;
    private javax.swing.JButton userButton;
    private javax.swing.JTextField userName;
    private javax.swing.JComboBox<String> yearBox;
    // End of variables declaration//GEN-END:variables

}
