/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentaccommodationsystem;

import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ghossain
 */
public class ShowFlat extends javax.swing.JFrame {

    String sname = null;
    String semail = null;
    
    String[] fid = new String[100000];
    
    DBConnect db=new DBConnect();
    
    public ShowFlat() {
        initComponents();
    }
    
    public ShowFlat(String email, String name) {
        initComponents();
        semail = email;
        sname = name;
        getFlat();
    }
    
    public void getFlat()
    {
        int count=0;
        String stat = "Verified";
        try{
                String sql="Select * from flatdetails where status = '"+stat+"';";
                ResultSet rs= db.getDetails(sql);
                DefaultTableModel tmodel=(DefaultTableModel) jTable1.getModel();
                tmodel.setRowCount(0);
                while(rs.next()){
                    String id = rs.getString("flatid");
                    fid[count] = id;
                    count++;
                    Object o[] = {rs.getString("title"), rs.getString("rent"), rs.getString("area"), rs.getString("date")};
                    tmodel.addRow(o);
                }  
            }
            catch(SQLException e){
                System.out.println("Error: "+e);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        searchButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Accommodation - Student");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel8.setText("Search Flat");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Area:");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Rent Range:");

        jComboBox1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Area", "Adabor", "Aftabnagar", "Agargaon", "Ahmed Nagar", "Ahmedbagh", "Alambagh", "Alamganj", "Alinagar", "Alu Bazar", "Amin Bagh", "Angur Jora", "Arambagh", "Asad Gate", "Ashiyan City", "Ashkona", "Ashrafabad", "Atipara", "Azimpur", "Babu Bazar", "Badda", "Baddanagar", "Bagbari", "Bahadurpur", "Baily Square", "Bakshi", "Banagram", "Banani", "Banani DOHS", "Banasree", "Bangla Bazar", "Bangla Motor", "Bangladesh Bank Colony", "Bangsal", "Banianagar", "Bank Colony", "Bara Katra", "Bara Maghbazar", "Barentek", "Baridhara", "Baridhara DOHS", "Bashabo", "Begum Bazar", "Begumganj", "Bibir Bazar", "Bijoynagar", "Boro Moghbazar", "Box Nagar", "Brahman Chiron", "Byshteki", "Chalk Bazar", "Chamilibagh", "Chankharpool", "Chhaya Bithi Housing", "Chhota Katra", "Chowdhury Para Malibagh", "Commissoner Bari", "Companiganj", "Court House Street", "D.I.T.Area", "Dakshin Khan", "Dakshin Mugda Para", "Dalpur", "Darus Salam", "Dawanpara", "Dayaganj", "Dhaka College Area", "Dhaka Medical College", "Dhalka Nagar", "Dhanmondi", "Dholairpar", "Dilkusha", "East Baragram", "Eskaton", "Faidabad", "Fakira Pool", "Farashganj", "Faridabad ", "Gabtoli ", "Ganaktuli ", "Gendaria ", "Goalghat ", "Goalnagar ", "Golartek ", "Goran ", "Gulbagh ", "Gulistan ", "Gulshan -1  ", "Gulshan-2 ", "Gupibagh Haji ", "Para Hasan Nagar ", "Hatirpool Bazar ", "Hatkhola Hazaribagh ", "Hazi Bari ", "Hazrat Nagar ", "Ibrahinpur ", "Islambagh ", "Islamnagar ", "Islampur ", "Jafrabad ", "Jaolahati ", "Jatrabari ", "Jeleypara ", "Jhigatola ", "Jurain ", "Kadamtala ", "Kafrul ", "Kakrail ", "Kalabagan ", "Kamalapur ", "Kaptan Bazar ", "Karatitola ", "Karimullah Bagh ", "Kather Pool ", "Kawranbazar ", "Kazipara ", "Khamer Bari", "Khilgaon ", "Khilkhat ", "Kumartuly ", "Kuril ", "Kusumbag ", "Lakshmi Bazar ", "Lalbagh ", "Lalmatia ", "Madartek ", "Madhu Bazar ", "Malibagh ", "Manikdey ", "Matikata ", "Mazibari ", "Meradia ", "Merul Badda ", "Middle Badda ", "Mir Hazirbagh ", "Mirpur Ceramic ", "Mirpur Colony ", "Mirpur Section-1 ", "Mirpur Section-10  ", "Mirpur Section-11 ", "Mirpur Section-12  ", "Mirpur Section-14 ", "Mirpur Section-2 ", "Mirpur Section-6  ", "Mirpur Section-7  ", "Mohakhali ", "Mohammadpur ", "Mokim Katra ", "Mominbagh ", "Moneshwar ", "Monipur ", "Monipuripara ", "Moshundi ", "Motijheil ", "Moulvi Bazar ", "Munshihati ", "Muradpur-1 ", "Muradpur-2 ", "Murgitola ", "Nabin Bag Bank Colony ", "Nadda Para ", "Namapara ", "Narinda ", "Nawab Katara ", "Nawabbari ", "Naya Bazar ", "Naya Paltan ", "Nazira Bazar ", "Newmarket ", "Neyatola ", "Niketan ", "Nikunjo ", "Nilkhet ", "Nilkhet ", "Babupura ", "North Badda ", "Nowagaon ", "Nowapara ", "Nurerchala ", "Paikpara ", "Parbata ", "Parer Bagh ", "Paribagh ", "Patuatuly ", "Pilkhana ", "Pollabi ", "Postagola ", "Purana Paltan ", "Puratan Mogultoli Purba ", "Purba ", "Razabazar ", "Rajarbagh ", "Ramna ", "Rampura ", "Rasulpur ", "Rayer Bazar ", "Rishi Para ", "Islamabed ", "Rokanpur ", "Royer Bazar ", "Staff Roysaheb Bazar ", "Rupnagar ", "Sabujbagh ", "Saidabad ", "Sawrapara ", "Science Laboratory ", "Segun Bagicha ", "Senpara ", "Shahidbagh ", "Shahidnagar ", "Shahjadpur ", "Shahjahanpur ", "Shakari Nagar ", "Shakertek ", "Shakhari Bazar  ", "Shamibagh ", "Shantibagh ", "Shantinagar ", "Shikaritola ", "Siddeswary ", "Siddique Bazar ", "Sonatengar ", "South Badda ", "Sowarighat ", "Sultanganj", "Takerhat", "Tallabagh ", "Taltola ", "Tegturipara ", "Tejkunipara ", "Tennery ", "Thatary Bazar ", "Topkhana ", "Uttar Khan ", "Uttar Mousondi ", "Uttara ABM City ", "Uttara Model Town ", "Vasantek ", "Wari" }));

        jTextField1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField1.setText(" ");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("to");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title", "Rent", "Area", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(250);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(25);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(30);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(25);
        }

        searchButton.setBackground(new java.awt.Color(255, 255, 255));
        searchButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back_icon.png"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(304, 304, 304)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        int count=0;
        String rentmin=jTextField1.getText();
        String rentmax=jTextField2.getText();
        String stat = "Verified";
        String rarea=jComboBox1.getSelectedItem().toString();
        
        if(!"".equals(rentmin) && !"".equals(rentmax) && !"Select Area".equals(rarea))
        {
            try{
                String sql="Select * from flatdetails where area='"+rarea+"' and rent between '"+rentmin+"' and '"+rentmax+"' and status = '"+stat+"';";
                ResultSet rs= db.getDetails(sql);
                DefaultTableModel tmodel=(DefaultTableModel) jTable1.getModel();
                tmodel.setRowCount(0);
                
                /*if(rs.next()== false)
                {
                    JOptionPane.showMessageDialog(this, "No Data Found");
                }
                else
                {
                    System.out.println("baal");
                    while(rs.next()){
                    System.out.println("baal");
                    String id = rs.getString("flatid");
                    fid[count] = id;
                    count++;
                    Object o[] = {rs.getString("title"), rs.getString("rent"), rs.getString("area"), rs.getString("date")};
                    tmodel.addRow(o);
                    }
                }
                rs.close();*/
                
                while(rs.next()){
                    String id = rs.getString("flatid");
                    fid[count] = id;
                    count++;
                    Object obj[] = {rs.getString("title"), rs.getString("rent"), rs.getString("area"), rs.getString("date")};
                    tmodel.addRow(obj);
                }
                  
            }
            catch(HeadlessException | SQLException e){
                System.out.println("Error: "+e);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Please give rent range and select area");        
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        StudentMainPage smp = new StudentMainPage(semail, sname);
        smp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
        DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
        int index = jTable1.getSelectedRow();
        
        String id = null;
        
        for(int i=0;i<fid.length;i++)
        {
            if(i==index)
            {
                id=fid[i];
            }
        }
        ShowFlatDetails sfd = new ShowFlatDetails(id, semail, sname);
        sfd.setVisible(true);
        //this.setEnabled(false);
        this.setVisible(false);
        // sfd.setDefaultCloseOperation(DISPOSE);
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowFlat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowFlat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowFlat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowFlat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowFlat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables
}
