/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentaccommodationsystem;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;


/**
 *
 * @author ghossain
 */


public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    
    DBConnect dbc = new DBConnect();
    
    public SignUp() {
        initComponents();
        pass_not_match.setVisible(false);
        shSelect.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        signup_name = new javax.swing.JTextField();
        signup_email = new javax.swing.JTextField();
        signup_phone = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        RegisterButton = new javax.swing.JButton();
        privacy_checkbox = new javax.swing.JCheckBox();
        BackButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        signup_password = new javax.swing.JPasswordField();
        signup_cpassword = new javax.swing.JPasswordField();
        show_pass_button = new javax.swing.JRadioButton();
        pass_not_match = new javax.swing.JLabel();
        studentButton = new javax.swing.JRadioButton();
        ownerButton = new javax.swing.JRadioButton();
        shSelect = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Accommodation");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        signup_name.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        signup_name.setForeground(new java.awt.Color(204, 204, 204));
        signup_name.setText("Name");
        signup_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                signup_nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                signup_nameFocusLost(evt);
            }
        });

        signup_email.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        signup_email.setForeground(new java.awt.Color(204, 204, 204));
        signup_email.setText("E-mail Address");
        signup_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                signup_emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                signup_emailFocusLost(evt);
            }
        });

        signup_phone.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        signup_phone.setForeground(new java.awt.Color(204, 204, 204));
        signup_phone.setText("Phone Number");
        signup_phone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                signup_phoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                signup_phoneFocusLost(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel1.setText("Name");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel2.setText("E-mail Address");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel3.setText("Phone Number");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel4.setText("Password");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel5.setText("Confirm Password");

        RegisterButton.setBackground(new java.awt.Color(51, 153, 0));
        RegisterButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        RegisterButton.setForeground(new java.awt.Color(255, 255, 255));
        RegisterButton.setText("Register");
        RegisterButton.setBorderPainted(false);
        RegisterButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegisterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegisterButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegisterButtonMouseExited(evt);
            }
        });
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });

        privacy_checkbox.setBackground(new java.awt.Color(255, 255, 255));
        privacy_checkbox.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        privacy_checkbox.setText("By checking, you agree to our Terms & Conditions and that you have read our Privacy Policy, including our Cookie Use.");
        privacy_checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                privacy_checkboxActionPerformed(evt);
            }
        });

        BackButton.setBackground(new java.awt.Color(255, 255, 255));
        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back_icon.png"))); // NOI18N
        BackButton.setBorderPainted(false);
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("New User! Registration Form");

        signup_password.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        signup_password.setForeground(new java.awt.Color(204, 204, 204));
        signup_password.setText("Password");
        signup_password.setPreferredSize(new java.awt.Dimension(110, 23));
        signup_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                signup_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                signup_passwordFocusLost(evt);
            }
        });
        signup_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_passwordActionPerformed(evt);
            }
        });

        signup_cpassword.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        signup_cpassword.setForeground(new java.awt.Color(204, 204, 204));
        signup_cpassword.setText("Confirm Password");
        signup_cpassword.setPreferredSize(new java.awt.Dimension(110, 23));
        signup_cpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                signup_cpasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                signup_cpasswordFocusLost(evt);
            }
        });

        show_pass_button.setBackground(new java.awt.Color(255, 255, 255));
        show_pass_button.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        show_pass_button.setText("Show Password");
        show_pass_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_pass_buttonActionPerformed(evt);
            }
        });

        pass_not_match.setBackground(new java.awt.Color(255, 255, 255));
        pass_not_match.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pass_not_match.setForeground(new java.awt.Color(255, 51, 51));
        pass_not_match.setText("*passwords not match");
        pass_not_match.setFocusable(false);
        pass_not_match.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                pass_not_matchComponentHidden(evt);
            }
        });

        studentButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(studentButton);
        studentButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        studentButton.setText("Student");

        ownerButton.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(ownerButton);
        ownerButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        ownerButton.setText("House Owner");

        shSelect.setBackground(new java.awt.Color(255, 255, 255));
        shSelect.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        shSelect.setForeground(new java.awt.Color(255, 51, 51));
        shSelect.setText("*choose one");

        jButton1.setBackground(new java.awt.Color(235, 47, 6));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cancel");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(studentButton)
                        .addGap(36, 36, 36)
                        .addComponent(ownerButton)
                        .addGap(18, 18, 18)
                        .addComponent(shSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel1)
                        .addGap(10, 10, 10)
                        .addComponent(signup_name, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(54, 54, 54)
                                        .addComponent(jLabel4)
                                        .addGap(10, 10, 10)
                                        .addComponent(signup_password, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(show_pass_button)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(pass_not_match))
                                            .addComponent(signup_cpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel3)
                                        .addGap(10, 10, 10)
                                        .addComponent(signup_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(38, 38, 38))
                            .addComponent(privacy_checkbox, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(signup_email, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(190, 190, 190)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(RegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(signup_name, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(signup_email, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studentButton)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ownerButton)
                        .addComponent(shSelect)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(signup_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signup_password, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signup_cpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pass_not_match)
                    .addComponent(show_pass_button, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(privacy_checkbox)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 255));
        jMenuBar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenuBar1MouseEntered(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setBackground(new java.awt.Color(204, 204, 255));
        jMenuItem1.setText("LogIn");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setBackground(new java.awt.Color(204, 204, 255));
        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signup_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signup_nameFocusGained
        // TODO add your handling code here:
        
        if(signup_name.getText().trim().equals("Name"))
        {
            signup_name.setText("");
            signup_name.setForeground(Color.BLACK);
        }
        
    }//GEN-LAST:event_signup_nameFocusGained

    private void signup_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signup_nameFocusLost
        // TODO add your handling code here:
        
        if(signup_name.getText().equals(""))
        {
            signup_name.setText("Name");
            signup_name.setForeground(new Color(204,204,204));
        }
        
    }//GEN-LAST:event_signup_nameFocusLost

    private void signup_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signup_emailFocusGained
        // TODO add your handling code here:
        
        if(signup_email.getText().trim().equals("E-mail Address"))
        {
            signup_email.setText("");
            signup_email.setForeground(Color.BLACK);
        }
        
    }//GEN-LAST:event_signup_emailFocusGained

    private void signup_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signup_emailFocusLost
        // TODO add your handling code here:
        
        if(signup_email.getText().equals(""))
        {
            signup_email.setText("E-mail Address");
            signup_email.setForeground(new Color(204,204,204));
        }
        
    }//GEN-LAST:event_signup_emailFocusLost

    private void signup_phoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signup_phoneFocusGained
        // TODO add your handling code here:
        
        if(signup_phone.getText().trim().equals("Phone Number"))
        {
            signup_phone.setText("");
            signup_phone.setForeground(Color.BLACK);
        }
        
    }//GEN-LAST:event_signup_phoneFocusGained

    private void signup_phoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signup_phoneFocusLost
        // TODO add your handling code here:
        
        if(signup_phone.getText().equals(""))
        {
            signup_phone.setText("Phone Number");
            signup_phone.setForeground(new Color(204,204,204));
        }
        
    }//GEN-LAST:event_signup_phoneFocusLost

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        
        LogIn lg = new LogIn();
        lg.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_BackButtonActionPerformed

    private void jMenuBar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBar1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuBar1MouseEntered

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        // TODO add your handling code here:
        
        String name = signup_name.getText();
        String email = signup_email.getText();
        String phnum = signup_phone.getText();
        String pass = signup_password.getText();
        String cpass = signup_cpassword.getText();
        
        ArrayList Details = new ArrayList();
        
        if(pass.equals(cpass) && privacy_checkbox.isSelected())
        {
            Details.add(name);
            Details.add(email);
            Details.add(phnum);
            Details.add(pass);
            int flag =0;
            if(ownerButton.isSelected())
            {
                flag = dbc.insertIntoHDB(Details, flag);
                shSelect.setVisible(false);
            }
            else if(studentButton.isSelected())
            {
                flag = dbc.insertIntoSDB(Details, flag);
                shSelect.setVisible(false);
            }
            else if(!ownerButton.isSelected() && !studentButton.isSelected())
            {
                shSelect.setVisible(true);
            }
            pass_not_match.setVisible(false);
            if(flag == 1)
            {
                LogIn lg = new LogIn();
                lg.setVisible(true);
                this.setVisible(false);
            }
            
        }
        else if(!pass.equals(cpass) && !privacy_checkbox.isSelected())
        {
            JOptionPane.showMessageDialog(this, "Please read & check the privacy box for Register And Correct your Password");
        }
        else if(!pass.equals(cpass))
        {
            pass_not_match.setVisible(true);
        }
        else if(!privacy_checkbox.isSelected())
        {
            JOptionPane.showMessageDialog(this, "Please read & check the privacy box for Register");
        }
        
        
    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void signup_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signup_passwordFocusGained
        // TODO add your handling code here:
        
        if(signup_password.getText().trim().equals("Password"))
        {
            signup_password.setText("");
            signup_password.setForeground(Color.BLACK);
        }
        
    }//GEN-LAST:event_signup_passwordFocusGained

    private void signup_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signup_passwordFocusLost
        // TODO add your handling code here:
        
        if(signup_password.getText().equals(""))
        {
            signup_password.setText("Password");
            signup_password.setForeground(new Color(204,204,204));
        }
        
    }//GEN-LAST:event_signup_passwordFocusLost

    private void signup_cpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signup_cpasswordFocusGained
        // TODO add your handling code here:
        
        if(signup_cpassword.getText().trim().equals("Confirm Password"))
        {
            signup_cpassword.setText("");
            signup_cpassword.setForeground(Color.BLACK);
        }
        
    }//GEN-LAST:event_signup_cpasswordFocusGained

    private void signup_cpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signup_cpasswordFocusLost
        // TODO add your handling code here:
        
        if(signup_cpassword.getText().equals(""))
        {
            signup_cpassword.setText("Confirm Password");
            signup_cpassword.setForeground(new Color(204,204,204));
        }
        
    }//GEN-LAST:event_signup_cpasswordFocusLost

    private void signup_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_passwordActionPerformed
        // TODO add your handling code here:
        
        /*if(signup_password.getText().equals("Password"))
        {
            signup_password.setEchoChar(("Password"));
        }*/
        
    }//GEN-LAST:event_signup_passwordActionPerformed

    private void show_pass_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_pass_buttonActionPerformed
        // TODO add your handling code here:
        
        if(show_pass_button.isSelected())
        {
            signup_password.setEchoChar((char)0);
            signup_cpassword.setEchoChar((char)0);
        }
        else
        {
            signup_password.setEchoChar('*');
            signup_cpassword.setEchoChar('*');
        }
        
    }//GEN-LAST:event_show_pass_buttonActionPerformed

    private void pass_not_matchComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pass_not_matchComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_not_matchComponentHidden

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        
        System.exit(0);
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        
        LogIn lg = new LogIn();
        lg.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void privacy_checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_privacy_checkboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_privacy_checkboxActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        LogIn lg = new LogIn();
        lg.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        
        jButton1.setBackground(new Color(232,65,24));
        
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        
        jButton1.setBackground(new Color(235, 47, 6));
        
    }//GEN-LAST:event_jButton1MouseExited

    private void RegisterButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterButtonMouseEntered
        // TODO add your handling code here:
        
        RegisterButton.setBackground(new Color(51,175,21));
        
    }//GEN-LAST:event_RegisterButtonMouseEntered

    private void RegisterButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterButtonMouseExited
        // TODO add your handling code here:
        
        RegisterButton.setBackground(new Color(51,153,0));
        
    }//GEN-LAST:event_RegisterButtonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton RegisterButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton ownerButton;
    private javax.swing.JLabel pass_not_match;
    private javax.swing.JCheckBox privacy_checkbox;
    private javax.swing.JLabel shSelect;
    private javax.swing.JRadioButton show_pass_button;
    private javax.swing.JPasswordField signup_cpassword;
    private javax.swing.JTextField signup_email;
    private javax.swing.JTextField signup_name;
    private javax.swing.JPasswordField signup_password;
    private javax.swing.JTextField signup_phone;
    private javax.swing.JRadioButton studentButton;
    // End of variables declaration//GEN-END:variables
}
