/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentaccommodationsystem;

import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author ghossain
 */
public class StudentMainPage extends javax.swing.JFrame {

    /**
     * Creates new form StudentMainPage
     */
    
    String semail = null;
    String sname = null;
    //String sid = null;
    String sStatus = null;
    //String sinsname = null;
    
    public StudentMainPage() {
        initComponents();
        userPanel.setVisible(false);
        userButton2.setVisible(false);
        studentDetails();
    }
    
    public StudentMainPage(String email, String name) {
        initComponents();
        userPanel.setVisible(false);
        userButton2.setVisible(false);
        semail = email;
        sname = name;
        jTextField2.setText(sname);
        studentDetails();
         if(sStatus.equals("Unverified")){
            statChecker.setVisible(true);
        }
        else{
            statChecker.setVisible(false);
        }
    }
    
    public void studentDetails()
    {
        DBConnect dbc = new DBConnect();
        try{
            String sql = "select * from studentdetails where email = '"+semail+"'";
            ResultSet rs = dbc.getDetails(sql);
            
            while(rs.next())
            {
                sStatus = rs.getString("status");
            }
        }catch(Exception e){
            System.out.println("Error : " + e);
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        userPanel = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        usericon2 = new javax.swing.JLabel();
        settingsButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        messButton = new javax.swing.JButton();
        flatButton = new javax.swing.JButton();
        subletButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        statChecker = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        userButton = new javax.swing.JButton();
        userButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Accommodation - Student");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userPanel.setBackground(new java.awt.Color(102, 115, 118));
        userPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(102, 115, 118));
        jTextField2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField2.setBorder(null);
        jTextField2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        userPanel.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 172, 30));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(102, 115, 118));
        jTextField3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField3.setText("Student");
        jTextField3.setToolTipText("");
        jTextField3.setBorder(null);
        jTextField3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        userPanel.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 50, 17));

        usericon2.setBackground(new java.awt.Color(204, 204, 204));
        usericon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/User2.png"))); // NOI18N
        usericon2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        userPanel.add(usericon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        settingsButton.setBackground(new java.awt.Color(102, 115, 118));
        settingsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/profile.png"))); // NOI18N
        settingsButton.setBorder(null);
        settingsButton.setBorderPainted(false);
        settingsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        settingsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settingsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settingsButtonMouseExited(evt);
            }
        });
        settingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButtonActionPerformed(evt);
            }
        });
        userPanel.add(settingsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        logoutButton.setBackground(new java.awt.Color(102, 115, 118));
        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Log Out.png"))); // NOI18N
        logoutButton.setBorder(null);
        logoutButton.setBorderPainted(false);
        logoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutButtonMouseExited(evt);
            }
        });
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        userPanel.add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        jPanel1.add(userPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, -1, 130));

        messButton.setBackground(new java.awt.Color(255, 255, 255));
        messButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Mess_Icon.png"))); // NOI18N
        messButton.setBorderPainted(false);
        messButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        messButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                messButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                messButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                messButtonMousePressed(evt);
            }
        });
        messButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messButtonActionPerformed(evt);
            }
        });
        jPanel1.add(messButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 150, 150));

        flatButton.setBackground(new java.awt.Color(255, 255, 255));
        flatButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Flat.png"))); // NOI18N
        flatButton.setBorderPainted(false);
        flatButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        flatButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                flatButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                flatButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                flatButtonMousePressed(evt);
            }
        });
        flatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flatButtonActionPerformed(evt);
            }
        });
        jPanel1.add(flatButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 150, 150));

        subletButton.setBackground(new java.awt.Color(255, 255, 255));
        subletButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Sub-Let.png"))); // NOI18N
        subletButton.setBorderPainted(false);
        subletButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        subletButton.setFocusable(false);
        subletButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        subletButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        subletButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                subletButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                subletButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                subletButtonMousePressed(evt);
            }
        });
        subletButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subletButtonActionPerformed(evt);
            }
        });
        jPanel1.add(subletButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 150, 150));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Select_Category.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 300, -1));

        statChecker.setBackground(new java.awt.Color(255, 255, 255));
        statChecker.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        statChecker.setForeground(new java.awt.Color(255, 0, 0));
        statChecker.setText("***Please give all details and wait 48 hours for verification***");
        jPanel1.add(statChecker, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 350, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 93, 660, 360));

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userButton.setBackground(new java.awt.Color(0, 151, 230));
        userButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user.png"))); // NOI18N
        userButton.setBorder(null);
        userButton.setBorderPainted(false);
        userButton.setContentAreaFilled(false);
        userButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                userButtonMouseReleased(evt);
            }
        });
        userButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userButtonActionPerformed(evt);
            }
        });
        jPanel2.add(userButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 50, 50));

        userButton2.setBackground(new java.awt.Color(0, 151, 230));
        userButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user.png"))); // NOI18N
        userButton2.setBorder(null);
        userButton2.setBorderPainted(false);
        userButton2.setContentAreaFilled(false);
        userButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userButton2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userButton2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                userButton2MouseReleased(evt);
            }
        });
        jPanel2.add(userButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 50, 50));

        jLabel3.setBackground(new java.awt.Color(0, 151, 230));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AppMemberlogo.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 500, 70));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 100));

        jMenu1.setText("File");

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void messButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_messButtonMouseEntered
        // TODO add your handling code here:

        messButton.setBackground(new Color(50,152,219));
        //ImageIcon ii = new ImageIcon(getClass().getResoources("/Images/Mess_icon_entered.png"));
        //jButton1.setIcon(ii);

    }//GEN-LAST:event_messButtonMouseEntered

    private void messButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_messButtonMouseExited
        // TODO add your handling code here:

        messButton.setBackground(Color.WHITE);

    }//GEN-LAST:event_messButtonMouseExited

    private void messButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_messButtonMousePressed
        // TODO add your handling code here:

        messButton.setBackground(new Color(52,157,195));

    }//GEN-LAST:event_messButtonMousePressed

    private void messButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messButtonActionPerformed
        // TODO add your handling code here:
        if("Verified".equals(sStatus))
        {
            ShowMess sm = new ShowMess(semail, sname);
            sm.setVisible(true);
            this.setVisible(false);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "You Are NOT Verified Yet");
        }
    }//GEN-LAST:event_messButtonActionPerformed

    private void flatButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flatButtonMouseEntered
        // TODO add your handling code here:

        flatButton.setBackground(new Color(50,152,219));

    }//GEN-LAST:event_flatButtonMouseEntered

    private void flatButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flatButtonMouseExited
        // TODO add your handling code here:

        flatButton.setBackground(Color.WHITE);

    }//GEN-LAST:event_flatButtonMouseExited

    private void flatButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flatButtonMousePressed
        // TODO add your handling code here:

        flatButton.setBackground(new Color(52,157,195));

    }//GEN-LAST:event_flatButtonMousePressed

    private void flatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flatButtonActionPerformed
        // TODO add your handling code here:

        if("Verified".equals(sStatus))
        {
            ShowFlat sf = new ShowFlat(semail, sname);
            sf.setVisible(true);
            this.setVisible(false);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "You Are NOT Verified Yet");
        }

    }//GEN-LAST:event_flatButtonActionPerformed

    private void subletButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subletButtonMouseEntered
        // TODO add your handling code here:

        subletButton.setBackground(new Color(50,152,219));

    }//GEN-LAST:event_subletButtonMouseEntered

    private void subletButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subletButtonMouseExited
        // TODO add your handling code here:

        subletButton.setBackground(Color.WHITE);

    }//GEN-LAST:event_subletButtonMouseExited

    private void subletButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subletButtonMousePressed
        // TODO add your handling code here:

        subletButton.setBackground(new Color(52,157,195));

    }//GEN-LAST:event_subletButtonMousePressed

    private void subletButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subletButtonActionPerformed
        // TODO add your handling code here:

        if("Verified".equals(sStatus))
        {
            ShowSublet ss = new ShowSublet(semail, sname);
            ss.setVisible(true);
            this.setVisible(false);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "You Are NOT Verified Yet");
        }

    }//GEN-LAST:event_subletButtonActionPerformed

    private void settingsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsButtonMouseEntered
        // TODO add your handling code here:

        settingsButton.setBackground(new Color(204,204,204));

    }//GEN-LAST:event_settingsButtonMouseEntered

    private void settingsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsButtonMouseExited
        // TODO add your handling code here:

        settingsButton.setBackground(new Color(102,115,118));

    }//GEN-LAST:event_settingsButtonMouseExited

    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
        // TODO add your handling code here:

        StudentProfile sp = new StudentProfile(semail, sname);
        sp.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_settingsButtonActionPerformed

    private void logoutButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseEntered
        // TODO add your handling code here:

        logoutButton.setBackground(new Color(204,204,204));

    }//GEN-LAST:event_logoutButtonMouseEntered

    private void logoutButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseExited
        // TODO add your handling code here:

        logoutButton.setBackground(new Color(102,115,118));

    }//GEN-LAST:event_logoutButtonMouseExited

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:

        LogIn lg = new LogIn();
        lg.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_logoutButtonActionPerformed

    private void userButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_userButtonMouseClicked

    private void userButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userButtonMouseEntered
        // TODO add your handling code here:

        userButton.setBackground(new Color(0, 151, 230));

    }//GEN-LAST:event_userButtonMouseEntered

    private void userButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userButtonMouseExited
        // TODO add your handling code here:

        userButton.setBackground(new Color(0, 151, 230));

    }//GEN-LAST:event_userButtonMouseExited

    private void userButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userButtonMousePressed
        // TODO add your handling code here:

        userButton.setBackground(new Color(253, 121, 168));
        userPanel.setVisible(true);
        userButton.setVisible(false);
        userButton2.setVisible(true);

    }//GEN-LAST:event_userButtonMousePressed

    private void userButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userButtonMouseReleased
        // TODO add your handling code here:

        userButton.setBackground(new Color(0, 151, 230));

    }//GEN-LAST:event_userButtonMouseReleased

    private void userButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userButtonActionPerformed

    private void userButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userButton2MouseEntered
        // TODO add your handling code here:

        userButton2.setBackground(new Color(0, 151, 230));

    }//GEN-LAST:event_userButton2MouseEntered

    private void userButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userButton2MouseExited
        // TODO add your handling code here:

        userButton2.setBackground(new Color(0, 151, 230));

    }//GEN-LAST:event_userButton2MouseExited

    private void userButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userButton2MousePressed
        // TODO add your handling code here:

        userButton2.setBackground(new Color(253, 121, 168));
        userPanel.setVisible(false);
        userButton2.setVisible(false);
        userButton.setVisible(true);

    }//GEN-LAST:event_userButton2MousePressed

    private void userButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userButton2MouseReleased
        // TODO add your handling code here:

        userButton2.setBackground(new Color(0, 151, 230));

    }//GEN-LAST:event_userButton2MouseReleased

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        
        userButton2.setBackground(new Color(253, 121, 168));
        userPanel.setVisible(false);
        userButton2.setVisible(false);
        userButton.setVisible(true);
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        
        userButton2.setBackground(new Color(253, 121, 168));
        userPanel.setVisible(false);
        userButton2.setVisible(false);
        userButton.setVisible(true);
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:

        System.exit(0);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentMainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton flatButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton messButton;
    private javax.swing.JButton settingsButton;
    private javax.swing.JLabel statChecker;
    private javax.swing.JButton subletButton;
    private javax.swing.JButton userButton;
    private javax.swing.JButton userButton2;
    private javax.swing.JPanel userPanel;
    private javax.swing.JLabel usericon2;
    // End of variables declaration//GEN-END:variables
}
