/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentaccommodationsystem;

import java.awt.Color;
import java.sql.ResultSet;

/**
 *
 * @author ghossain
 */
public class StudentProfile extends javax.swing.JFrame {

    /**
     * Creates new form StudentProfile
     */
    
    DBConnect dbc = new DBConnect();
    String semail = null;
    String sname = null;
    String stat = null;
    
    public StudentProfile() {
        initComponents();
        userPanel.setVisible(false);
        userButton2.setVisible(false);
        setProfile();
    }
    
    public StudentProfile(String email, String name) {
        initComponents();
        userPanel.setVisible(false);
        userButton2.setVisible(false);
        semail = email;
        sname = name;
        userName.setText(sname);
        username.setText(sname);
        setProfile();
        if("Verified".equals(stat))
        {
            verified.setVisible(true);
            unverified.setVisible(false);
        }
        else if("Unverified".equals(stat))
        {
            unverified.setVisible(true);
            verified.setVisible(false);
        }
    }
    
    public void setProfile()
    {
        //System.out.println(hemail);
        try{
            String sql= "Select * from studentdetails where email ='"+semail+"'";
            ResultSet rs = dbc.getDetails(sql);
            
            while(rs.next())
            {
                name.setText(rs.getString("name"));
                email.setText(rs.getString("email"));
                phone.setText(rs.getString("phonenumber"));
                nid.setText(rs.getString("nid"));
                studentid.setText(rs.getString("studentid"));
                instname.setText(rs.getString("institutename"));
                address.setText(rs.getString("address"));
                stat = rs.getString("status");
            }
        }catch(Exception e){
            System.out.println("Error : " + e);
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        userButton = new javax.swing.JButton();
        userName = new javax.swing.JTextField();
        userButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        userPanel = new javax.swing.JPanel();
        username = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        usericon2 = new javax.swing.JLabel();
        settingsButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        updateInfo = new javax.swing.JButton();
        nid = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        studentid = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        instname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        verified = new javax.swing.JLabel();
        unverified = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Accommodation - Student");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userButton.setBackground(new java.awt.Color(0, 151, 230));
        userButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user.png"))); // NOI18N
        userButton.setBorder(null);
        userButton.setBorderPainted(false);
        userButton.setContentAreaFilled(false);
        userButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                userButtonMouseReleased(evt);
            }
        });
        userButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userButtonActionPerformed(evt);
            }
        });
        jPanel2.add(userButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 50, 50));

        userName.setEditable(false);
        userName.setBackground(new java.awt.Color(102, 153, 255));
        userName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        userName.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        userName.setBorder(null);
        userName.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userNameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userNameMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userNameMousePressed(evt);
            }
        });
        jPanel2.add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 250, -1));

        userButton2.setBackground(new java.awt.Color(0, 151, 230));
        userButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user.png"))); // NOI18N
        userButton2.setBorder(null);
        userButton2.setBorderPainted(false);
        userButton2.setContentAreaFilled(false);
        userButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userButton2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userButton2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                userButton2MouseReleased(evt);
            }
        });
        jPanel2.add(userButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 50, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 80));

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setBorder(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setAutoscrolls(true);
        jPanel1.setPreferredSize(new java.awt.Dimension(630, 400));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userPanel.setBackground(new java.awt.Color(102, 115, 118));
        userPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username.setEditable(false);
        username.setBackground(new java.awt.Color(102, 115, 118));
        username.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        username.setBorder(null);
        username.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        userPanel.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 172, 30));

        status.setEditable(false);
        status.setBackground(new java.awt.Color(102, 115, 118));
        status.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        status.setForeground(new java.awt.Color(255, 255, 255));
        status.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        status.setText("Student");
        status.setToolTipText("");
        status.setBorder(null);
        status.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        userPanel.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 172, 17));

        usericon2.setBackground(new java.awt.Color(204, 204, 204));
        usericon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/User2.png"))); // NOI18N
        usericon2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userPanel.add(usericon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        settingsButton.setBackground(new java.awt.Color(102, 115, 118));
        settingsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/profile.png"))); // NOI18N
        settingsButton.setBorder(null);
        settingsButton.setBorderPainted(false);
        settingsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        settingsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settingsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settingsButtonMouseExited(evt);
            }
        });
        settingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButtonActionPerformed(evt);
            }
        });
        userPanel.add(settingsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        logoutButton.setBackground(new java.awt.Color(102, 115, 118));
        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Log Out.png"))); // NOI18N
        logoutButton.setBorder(null);
        logoutButton.setBorderPainted(false);
        logoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutButtonMouseExited(evt);
            }
        });
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        userPanel.add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        jPanel1.add(userPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, -1, 130));

        homeButton.setBackground(new java.awt.Color(255, 255, 255));
        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home_button.png"))); // NOI18N
        homeButton.setBorderPainted(false);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));

        address.setEditable(false);
        address.setColumns(20);
        address.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        address.setRows(5);
        address.setTabSize(4);
        address.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setViewportView(address);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 400, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("   Address:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, 30));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("E-mail:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, 30));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Phone:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, 30));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("NID:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 60, 30));

        updateInfo.setText("Update Information");
        updateInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateInfoActionPerformed(evt);
            }
        });
        jPanel1.add(updateInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, -1, 42));

        nid.setEditable(false);
        nid.setBackground(new java.awt.Color(255, 255, 255));
        nid.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nid.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(nid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 400, 30));

        phone.setEditable(false);
        phone.setBackground(new java.awt.Color(255, 255, 255));
        phone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        phone.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 400, 30));

        email.setEditable(false);
        email.setBackground(new java.awt.Color(255, 255, 255));
        email.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        email.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 400, 30));

        name.setEditable(false);
        name.setBackground(new java.awt.Color(255, 255, 255));
        name.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        name.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 400, 30));

        studentid.setEditable(false);
        studentid.setBackground(new java.awt.Color(255, 255, 255));
        studentid.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        studentid.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(studentid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 400, 30));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Student ID:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, 30));

        instname.setEditable(false);
        instname.setBackground(new java.awt.Color(255, 255, 255));
        instname.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        instname.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(instname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 400, 30));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Institute Name:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, 30));

        verified.setBackground(new java.awt.Color(0, 204, 0));
        verified.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        verified.setForeground(new java.awt.Color(255, 255, 255));
        verified.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        verified.setText("Verified");
        verified.setOpaque(true);
        jPanel1.add(verified, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 140, 40));

        unverified.setBackground(new java.awt.Color(255, 0, 0));
        unverified.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        unverified.setForeground(new java.awt.Color(255, 255, 255));
        unverified.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        unverified.setText("Unverified");
        unverified.setOpaque(true);
        jPanel1.add(unverified, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 140, 40));

        jScrollPane3.setViewportView(jPanel1);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 630, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void settingsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsButtonMouseEntered
        // TODO add your handling code here:

        settingsButton.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_settingsButtonMouseEntered

    private void settingsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsButtonMouseExited
        // TODO add your handling code here:

        settingsButton.setBackground(new Color(102,115,118));
    }//GEN-LAST:event_settingsButtonMouseExited

    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
        // TODO add your handling code here:

        StudentProfile sp = new StudentProfile(semail, sname);
        sp.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_settingsButtonActionPerformed

    private void logoutButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseEntered
        // TODO add your handling code here:

        logoutButton.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_logoutButtonMouseEntered

    private void logoutButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseExited
        // TODO add your handling code here:

        logoutButton.setBackground(new Color(102,115,118));
    }//GEN-LAST:event_logoutButtonMouseExited

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:

        LogIn lg = new LogIn();
        lg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void userButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_userButtonMouseClicked

    private void userButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userButtonMouseEntered
        // TODO add your handling code here:

        userButton.setBackground(new Color(0, 151, 230));
        userName.setForeground(new Color(3,118,3));
    }//GEN-LAST:event_userButtonMouseEntered

    private void userButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userButtonMouseExited
        // TODO add your handling code here:

        userButton.setBackground(new Color(0, 151, 230));
        userName.setForeground(Color.BLACK);
    }//GEN-LAST:event_userButtonMouseExited

    private void userButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userButtonMousePressed
        // TODO add your handling code here:

        userButton.setBackground(new Color(253, 121, 168));
        userPanel.setVisible(true);
        userButton.setVisible(false);
        userButton2.setVisible(true);
    }//GEN-LAST:event_userButtonMousePressed

    private void userButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userButtonMouseReleased
        // TODO add your handling code here:

        userButton.setBackground(new Color(0, 151, 230));
    }//GEN-LAST:event_userButtonMouseReleased

    private void userButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userButtonActionPerformed

    private void userNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userNameMouseEntered
        // TODO add your handling code here:

        userName.setForeground(new Color(3,118,3));
    }//GEN-LAST:event_userNameMouseEntered

    private void userNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userNameMouseExited
        // TODO add your handling code here:

        userName.setForeground(Color.BLACK);
    }//GEN-LAST:event_userNameMouseExited

    private void userNameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userNameMousePressed
        // TODO add your handling code here:

        userButton.setBackground(new Color(253, 121, 168));
        userPanel.setVisible(true);
        userButton.setVisible(false);
        userButton2.setVisible(true);
    }//GEN-LAST:event_userNameMousePressed

    private void userButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userButton2MouseEntered
        // TODO add your handling code here:

        userButton2.setBackground(new Color(0, 151, 230));
        userName.setForeground(new Color(3,118,3));
    }//GEN-LAST:event_userButton2MouseEntered

    private void userButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userButton2MouseExited
        // TODO add your handling code here:

        userButton2.setBackground(new Color(0, 151, 230));
        userName.setForeground(Color.BLACK);
    }//GEN-LAST:event_userButton2MouseExited

    private void userButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userButton2MousePressed
        // TODO add your handling code here:

        userButton2.setBackground(new Color(253, 121, 168));
        userPanel.setVisible(false);
        userButton2.setVisible(false);
        userButton.setVisible(true);
    }//GEN-LAST:event_userButton2MousePressed

    private void userButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userButton2MouseReleased
        // TODO add your handling code here:

        userButton2.setBackground(new Color(0, 151, 230));
    }//GEN-LAST:event_userButton2MouseReleased

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:

        StudentMainPage smp = new StudentMainPage(semail, sname);
        smp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeButtonActionPerformed

    private void updateInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateInfoActionPerformed
        // TODO add your handling code here:

        StudentUpdateProfile sup = new StudentUpdateProfile(semail, sname);
        sup.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_updateInfoActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        
        userButton2.setBackground(new Color(253, 121, 168));
        userPanel.setVisible(false);
        userButton2.setVisible(false);
        userButton.setVisible(true);
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        
        userButton2.setBackground(new Color(253, 121, 168));
        userPanel.setVisible(false);
        userButton2.setVisible(false);
        userButton.setVisible(true);
    }//GEN-LAST:event_jPanel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea address;
    private javax.swing.JTextField email;
    private javax.swing.JButton homeButton;
    private javax.swing.JTextField instname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton logoutButton;
    private javax.swing.JTextField name;
    private javax.swing.JTextField nid;
    private javax.swing.JTextField phone;
    private javax.swing.JButton settingsButton;
    private javax.swing.JTextField status;
    private javax.swing.JTextField studentid;
    private javax.swing.JLabel unverified;
    private javax.swing.JButton updateInfo;
    private javax.swing.JButton userButton;
    private javax.swing.JButton userButton2;
    private javax.swing.JTextField userName;
    private javax.swing.JPanel userPanel;
    private javax.swing.JLabel usericon2;
    private javax.swing.JTextField username;
    private javax.swing.JLabel verified;
    // End of variables declaration//GEN-END:variables
}
