/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import studentaccommodationsystem.LogIn;

/**
 *
 * @author ghossain
 */
public class AdminLogIn extends javax.swing.JFrame {

    /**
     * Creates new form AdminLogIn
     */
    
    AdminDBConnect adbc = new AdminDBConnect();
    
    public AdminLogIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        login_email = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        login_password = new javax.swing.JPasswordField();
        show_pass_button = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        memberlogin = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Accommodation - Admin");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Sign In to Your Account", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Arial", 0, 24))); // NOI18N
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login_email.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        login_email.setForeground(new java.awt.Color(204, 204, 204));
        login_email.setText("E-mail Address");
        login_email.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        login_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                login_emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                login_emailFocusLost(evt);
            }
        });
        login_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                login_emailKeyPressed(evt);
            }
        });
        jPanel1.add(login_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 396, 39));

        loginButton.setBackground(new java.awt.Color(51, 153, 0));
        loginButton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("LogIn");
        loginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        loginButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loginButtonKeyPressed(evt);
            }
        });
        jPanel1.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 396, 43));

        login_password.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        login_password.setForeground(new java.awt.Color(204, 204, 204));
        login_password.setText("Password");
        login_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                login_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                login_passwordFocusLost(evt);
            }
        });
        login_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                login_passwordKeyPressed(evt);
            }
        });
        jPanel1.add(login_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 396, 39));

        show_pass_button.setBackground(new java.awt.Color(255, 255, 255));
        show_pass_button.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        show_pass_button.setText("Show Password");
        show_pass_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_pass_buttonActionPerformed(evt);
            }
        });
        show_pass_button.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                show_pass_buttonKeyPressed(evt);
            }
        });
        jPanel1.add(show_pass_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jMenu1.setText("File");

        memberlogin.setText("Member LogIn");
        memberlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberloginActionPerformed(evt);
            }
        });
        jMenu1.add(memberlogin);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void login_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_login_emailFocusGained
        // TODO add your handling code here:

        if(login_email.getText().equals("E-mail Address"))
        {
            login_email.setText("");
            login_email.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_login_emailFocusGained

    private void login_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_login_emailFocusLost
        // TODO add your handling code here:

        if(login_email.getText().equals(""))
        {
            login_email.setText("E-mail Address");
            login_email.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_login_emailFocusLost

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:

        String email = login_email.getText();
        String pass = login_password.getText();
        String dpass = null;
        String name = null;

        try{
            ResultSet rs = adbc.logInToAdmin(email);
            while(rs.next())
            {
                dpass = rs.getString("password");
                name = rs.getString("name");
            }

            if(pass.equals(dpass))
            {
                JOptionPane.showMessageDialog(this, "LogIn Succesfully");
                AdminMainPage amp = new AdminMainPage(email, name);
                amp.setVisible(true);
                this.setVisible(false);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Email or Password Incorrect");
            }

            }catch(Exception e){
                System.out.println("Error : " + e);
                e.printStackTrace();
            }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void login_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_login_passwordFocusGained
        // TODO add your handling code here:

        if(login_password.getText().trim().equals("Password"))
        {
            login_password.setText("");
            login_password.setForeground(Color.BLACK);
        }

    }//GEN-LAST:event_login_passwordFocusGained

    private void login_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_login_passwordFocusLost
        // TODO add your handling code here:

        if(login_password.getText().trim().equals(""))
        {
            login_password.setText("Password");
            login_password.setForeground(new Color(204,204,204));
        }

    }//GEN-LAST:event_login_passwordFocusLost

    private void login_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_login_passwordKeyPressed
        // TODO add your handling code here:

        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            loginButton.doClick();
        }

    }//GEN-LAST:event_login_passwordKeyPressed

    private void show_pass_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_pass_buttonActionPerformed
        // TODO add your handling code here:

        if(show_pass_button.isSelected())
        {
            login_password.setEchoChar((char)0);
        }
        else
        {
            login_password.setEchoChar('*');
        }

    }//GEN-LAST:event_show_pass_buttonActionPerformed

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
        // TODO add your handling code here:

        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            loginButton.doClick();
        }

    }//GEN-LAST:event_jPanel1KeyPressed

    private void login_emailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_login_emailKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            loginButton.doClick();
        }
    }//GEN-LAST:event_login_emailKeyPressed

    private void memberloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberloginActionPerformed
        // TODO add your handling code here:
        
        LogIn lg = new LogIn();
        lg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_memberloginActionPerformed

    private void show_pass_buttonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_show_pass_buttonKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            loginButton.doClick();
        }
    }//GEN-LAST:event_show_pass_buttonKeyPressed

    private void loginButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginButtonKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            loginButton.doClick();
        }
    }//GEN-LAST:event_loginButtonKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField login_email;
    private javax.swing.JPasswordField login_password;
    private javax.swing.JMenuItem memberlogin;
    private javax.swing.JRadioButton show_pass_button;
    // End of variables declaration//GEN-END:variables
}
